### ISSUE TITLE
Confused about copy.deepcopy operations in train_erase.py

### ISSUE THREAD

**Issue by CharlesGong12** [rohitgandikota/unified-concept-editing#13]
Hi! 
What an amazing work! I am an undergrad learning about your code and get confused about the copy.deepcopy operations in function edit_model, train_erase.py. I think projection_matrices contains the deepcopy of params in unet, so the modification of items in projection_matrices will not affect unet or ldm_stable. But it turns out that ldm_stable is actually edited after func train_erase.
Looking forward to your reply. Thx!! ^^

**Comment by rohitgandikota** [comment]
Hi, 

That's a good question! The copy.deepcopy is just to store a copy of the original weights! 

If you look at it carefully, you will find that the `projection_matrices` is the variable we are using to edit the weights, which is built from the layers in `ca_layers` variable. This `ca_layers` is not a deepcopy. It is simply a collection of layers from the pre-trained model. 

Hope that made sense!

**Comment by CharlesGong12** [comment]
Hi, thanks for your reply!
I am still confused. In [line 190](https://github.com/rohitgandikota/unified-concept-editing/blob/main/train-scripts/train_erase.py#L190), the `projection_matrices` is indeed built from `ca_layers`. But in [line 200](https://github.com/rohitgandikota/unified-concept-editing/blob/main/train-scripts/train_erase.py#L200), the element of `projection_matrices` is assigned as `l.to_v`, a deepcopy from `og_matrices`. So I think the elements of `projection_matrices` are deepcopy too. Idk if there is any deviation in my understanding?
Thanks again for your answer!

**Comment by rohitgandikota** [comment]
`l.to_k` is the actual model's layer. We are simply setting its weights (which are numbers) to the og_matrices values. This line can be deleted in erasing code but it has some significance in debiasing code. For example, in debiasing code, we edit the weights, check the ratios, and then we reset it back to the original weights. In that case, we use `l.to_k = og_matrices[idx]`. We can also simply delete the model and reload it using diffusers, but it takes some compute time.

So basically, before editing, we are just resetting the weights to the original weights. But since `projection_matrices` hold the layer weights after we are resetting, think of `projection_matrices` as looking into the model and storing whatever weights we set it as. In fact, in this line https://github.com/rohitgandikota/unified-concept-editing/blob/f7222e63fc01fee426a61a90c0215edacbe983b6/train-scripts/train_erase.py#L191, we can see og_matrices are coming from `l.to_k` directly. Therefore any changes to projection_matrices will change the weights of `l.to_k` - which is a layer from the model we are editing.

**Comment by CharlesGong12** [comment]
Hi, thanks for your patient explanation!
Can I understand as that the operation on deepcopy will directly modify the parameters of SD?

**Comment by rohitgandikota** [comment]
Let's focus only on `l.to_k` for now. If you change the values of `l.to_k` you will change the model. 

first we changed it to some deepcopy weights. So the original model has changed to that set of weights

next we changed it based on UCE formulation. Now the original model is again changed. 


The key for understanding here is that we are changing the `l.to_k` weights. the value does not matter - as long as we are directly calling `l.to_k` and changing its values, the original model is updated
