### ISSUE TITLE
Confused about the logic in edit_model.py

### ISSUE THREAD

**Issue by Hzj199** [rohitgandikota/unified-concept-editing#3]
Hi, thank you for the great work! I've been using your library and it has been really helpful. While working with it, I came across something I wasn't sure about. 

Are the obtained new_emb and old_emb corresponding to the [pad] part?

https://github.com/rohitgandikota/unified-concept-editing/blob/b66412e9c89f0f1b5aceed626aa25bf7c0bd5631/train-scripts/train_erase.py#L253C1-L260C104

**Comment by rohitgandikota** [comment]
They correspond to the final token and the some of the padding tokens (how much ever to match both the lengths). For example: in the figure below, if the top embeddings representing old_emb (concept embeddings) has 4 tokens and the bottom one representing new_emb (or target embeddings) has only 2, we take only enough paddings for new so that the length matches with old. Hope that made sense!

<img width="668" alt="image" src="https://github.com/rohitgandikota/unified-concept-editing/assets/17539718/fed2dc7c-e6f3-4ba4-ba73-a14e5f930b14">

**Comment by Hzj199** [comment]
Thank you so much for the detailed explanation! I appreciate your prompt response and help on this matter.
I'm not deeply familiar with NLP. I have another question though: Why not use the first 4 tokens?

**Comment by rohitgandikota** [comment]
Then you might be replacing the last 2 tokens with the padding - this will be a problem when u use these tokens in a long sentence. Next time the model sees a prompt with last 2 tokens, it will discard all the other tokens that follows them as it things that could be the ending token.

**Comment by SLU010** [comment]
Hi, could you explain a bit about the intuition for keeping the original <startoftext> embedding unchanged?

**Comment by rohitgandikota** [comment]
We are altering the weights such that the layer outputs differently for the embeddings that we wish to edit and same for the embeddings we dont

**Comment by SLU010** [comment]
Thanks for your reply! Sorry that I didn't make my question clear.  

I realize that your method involves altering the weights, but I'm a bit confused about why the mapping starts from `final_token_idx` and `final_token_idx_new` [here](https://github.com/rohitgandikota/unified-concept-editing/blob/b66412e9c89f0f1b5aceed626aa25bf7c0bd5631/train-scripts/train_erase.py#L253C1-L260C104). It seems that this generally disregards the embedding of the start-of-text token. Based on the figure you provided, it appears that only the final embeddings of the text and padding elements are being considered. 

Would you mind clarifying this a bit? Thanks!

**Comment by rohitgandikota** [comment]
When the concept has multiple tokens, if we consider the final embedding, then we would be changing the concept not the individual tokens. Consider "Van Gogh" for example, if we change the embedding from the last token, we will not be altering "Van" (which can mean other things). Also since text embedders are sequential processors, the "Gogh" token embedding has information of "van". We are not really changing "Gogh", but we are in fact changing the "Van Gogh" together. Hope that made sense

**Comment by SLU010** [comment]
Quite clear! Thanks :)

> When the concept has multiple tokens, if we consider the final embedding, then we would be changing the concept not the individual tokens. Consider "Van Gogh" for example, if we change the embedding from the last token, we will not be altering "Van" (which can mean other things). Also since text embedders are sequential processors, the "Gogh" token embedding has information of "van". We are not really changing "Gogh", but we are in fact changing the "Van Gogh" together. Hope that made sense
